import { Inter, Sacramento } from "next/font/google";
import "./globals.css";
import { RedditProvider } from "./contexts/RedditContext";
import { UserProvider } from "@auth0/nextjs-auth0/client";
// import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Reddit Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		// <NextUIProvider>
		<UserProvider>
			<RedditProvider>
				<html
					className="bg-[rgb(24,26,27)] text-white overflow-hidden font-sf-pro"
					//style={{ fontFamily: "sans-serif" }}
					lang="en">
					<body className={inter.className}>{children}</body>
				</html>
			</RedditProvider>
		</UserProvider>
		// </NextUIProvider>
	);
}
